name: "Testing"
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run chromatic test
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run build-css
      - run: npm run chromatic
        env:
          CHROMATIC_APP_CODE: ${{ secrets.CHROMATIC_APP_CODE }}
          CI: true
